spring:
  application:
    name: Triangle
  datasource:
    url: jdbc:postgresql://localhost:5432/Triangle
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
